export const ENVIRONMENT_PRESETS = ['studio', 'apartment', 'city', 'warehouse', 'lobby', 'park', 'forest', 'sunset', 'dawn', 'night']

export const CAMERA_SHOTS = [
  { label: 'Start shot', value: 'outsideShot' },
  { label: 'Push-in shot', value: 'pushShot' },
  { label: 'Entering shot', value: 'enteringShot' },
  { label: 'Inside shot', value: 'insideShot' },
]

export const DEFAULT_CAMERA_SHOTS = {
  outsideShot: {
    position: [6.2, 2.45, 0],
    lookAt: [0.02, 1.85, 0],
    fov: 44,
  },
  pushShot: {
    position: [4.25, 2.18, 0],
    lookAt: [0.02, 1.62, 0],
    fov: 45,
  },
  enteringShot: {
    position: [-0.183, 2.248, -0.019],
    lookAt: [-2.35, 2.4, 0],
    fov: 52,
  },
  insideShot: {
    position: [-1.885, 2.367, -0.004],
    lookAt: [-2.35, 2.4, 0],
    fov: 52,
  },
}

export const DEFAULT_TUNING = {
  previewMode: 'sequence',
  cameraShots: DEFAULT_CAMERA_SHOTS,
  environment: 'night',
  background: '#000000',
  exposure: 1.79,
  environmentIntensity: 1.23,
  ambient: 0.8,
  key: 0.39,
  cyan: 0,
  cabin: 0,
  contactShadow: 0.32,
  sequenceRunId: 0,
  sequenceSpeed: 1,
  cameraSmooth: 4.2,
  cameraFov: 52,
  doorOpen: 0,
  materialLift: 0.12,
  metalRoughness: 1,
  mirrorFxAngle: 135,
  mirrorFxColor: '#ffffff',
  mirrorFxDelay: 0,
  mirrorFxGuide: false,
  mirrorFxOpacity: 1.45,
  mirrorFxPlaneHeight: 2.16,
  mirrorFxPlaneWidth: 2.16,
  mirrorFxPreviewRunId: 0,
  mirrorFxProgress: 0.26,
  mirrorFxRotationX: 0,
  mirrorFxRotationY: 90,
  mirrorFxRotationZ: 0,
  mirrorFxSeconds: 0.85,
  mirrorFxSoftness: 0.12,
  mirrorFxWidth: 0.01,
  mirrorFxX: -2.65,
  mirrorFxY: 2.47,
  mirrorFxZ: -0.03,
  openDelay: 0.35,
  openSeconds: 3,
  portfolioScreenGuide: true,
  portfolioScreenHeight: 3200,
  portfolioScreenScale: 0.0138,
  portfolioScreenWidth: 2600,
  portfolioScreenX: -2.725,
  portfolioScreenY: 2.3,
  portfolioScreenZ: 0,
  enterDelay: 0.2,
  enterSeconds: 2.15,
  turnSeconds: 1.8,
  closeDelay: 0.1,
  closeSeconds: 1.4,
}

export const ORIGINAL_TUNING = {
  ...DEFAULT_TUNING,
  environment: 'studio',
  background: '#11141b',
  exposure: 1,
  environmentIntensity: 1,
  ambient: 0.62,
  key: 2.5,
  cyan: 1.15,
  cabin: 0.9,
  cameraFov: 44,
  doorOpen: 0,
  materialLift: 0,
  metalRoughness: 0,
}
