export const ENVIRONMENT_PRESETS = ['custom', 'studio', 'apartment', 'city', 'warehouse', 'lobby', 'park', 'forest', 'sunset', 'dawn', 'night']

export const TONE_MAPPING_OPTIONS = ['agx', 'aces', 'neutral']

export const PRACTICAL_STYLE_OPTIONS = ['cylinder', 'band', 'slots', 'off']

export const MODAL_EASE_OPTIONS = ['power1.inOut', 'power2.inOut', 'power2.out', 'power3.out', 'power4.out', 'expo.out', 'sine.inOut', 'none']

export const CAMERA_SHOTS = [
  { label: 'Start shot', value: 'outsideShot' },
  { label: 'Push-in shot', value: 'pushShot' },
  { label: 'Entering shot', value: 'enteringShot' },
  { label: 'Inside shot', value: 'insideShot' },
]

export const DEFAULT_CAMERA_SHOTS = {
  outsideShot: {
    position: [6.2, 2.45, 0],
    lookAt: [0.02, 1.85, 0],
    fov: 44,
  },
  pushShot: {
    position: [4.25, 2.18, 0],
    lookAt: [0.02, 1.62, 0],
    fov: 45,
  },
  enteringShot: {
    position: [-0.183, 2.248, -0.019],
    lookAt: [-2.35, 2.4, 0],
    fov: 52,
  },
  insideShot: {
    position: [-1.885, 2.367, -0.004],
    lookAt: [-2.35, 2.4, 0],
    fov: 52,
  },
}

export const DEFAULT_TUNING = {
  previewMode: 'sequence',
  cameraShots: DEFAULT_CAMERA_SHOTS,
  environment: 'custom',
  background: '#000000',
  wallColor: '#2e261d',
  floorColor: '#191410',
  toneMapping: 'agx',
  aoIntensity: 5.3,
  bloomIntensity: 0.25,
  vignetteDarkness: 1,
  exposure: 1.79,
  environmentIntensity: 1.23,
  ambient: 0.8,
  key: 0.28,
  cyan: 0,
  cabin: 0,
  contactShadow: 0.32,
  sequenceRunId: 0,
  sequenceSpeed: 1,
  cameraSmooth: 4.2,
  cameraFov: 52,
  doorOpen: 0,
  materialLift: 0.18,
  metalPolish: 1,
  metalRoughness: 0.16,
  hallDressing: true,
  dressingFoliageHeight: 0.62,
  dressingFoliageScale: 1.45,
  dressingFoliageTurn: 0,
  practicalStyle: 'cylinder',
  practicalAngle: 0.55,
  practicalIntensity: 40,
  practicalColor: '#ff9d3f',
  practicalHeight: 1.82,
  mirrorFxAngle: 135,
  mirrorFxColor: '#ffffff',
  mirrorFxDelay: 0,
  mirrorFxGuide: false,
  mirrorFxOpacity: 1.45,
  mirrorFxPlaneHeight: 2.16,
  mirrorFxPlaneWidth: 2.16,
  mirrorFxPreviewRunId: 0,
  mirrorFxProgress: 0.26,
  mirrorFxRotationX: 0,
  mirrorFxRotationY: 90,
  mirrorFxRotationZ: 0,
  mirrorFxSeconds: 0.85,
  mirrorFxSoftness: 0.12,
  mirrorFxWidth: 0.01,
  mirrorFxX: -2.65,
  mirrorFxY: 2.47,
  mirrorFxZ: -0.03,
  modalBandAngle: 135,
  modalBandColor: '#ffe7c2',
  modalBandOpacity: 0.9,
  modalBandSoftness: 6,
  modalBandWidth: 10,
  modalCloseSeconds: 0.9,
  modalEase: 'power2.inOut',
  modalRevealDelay: 0.35,
  modalRevealSeconds: 1.2,
  openDelay: 0.35,
  openSeconds: 3,
  enterDelay: 0.2,
  enterSeconds: 2.15,
  turnSeconds: 1.8,
  closeDelay: 0.1,
  closeSeconds: 1.4,
}

export const ORIGINAL_TUNING = {
  ...DEFAULT_TUNING,
  environment: 'studio',
  background: '#11141b',
  wallColor: null,
  floorColor: null,
  toneMapping: 'aces',
  aoIntensity: 0,
  bloomIntensity: 0,
  vignetteDarkness: 0,
  exposure: 1,
  environmentIntensity: 1,
  ambient: 0.62,
  key: 2.5,
  cyan: 1.15,
  cabin: 0.9,
  cameraFov: 44,
  doorOpen: 0,
  materialLift: 0,
  metalPolish: 0,
  metalRoughness: 0,
  practicalStyle: 'off',
  hallDressing: false,
}
